apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alejo-maya/argocd-app-test.git
    targetRevision: HEAD
    path: workflows
  destination: 
    server: https://kubernetes.default.svc
    namespace: workflows

  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
