apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app02-argo-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alejo-maya/argocd-app-test.git
    targetRevision: HEAD
    path: node
  destination: 
    server: https://kubernetes.default.svc
    namespace: app02

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
